INSERT INTO exchange_api_endpoints (
    exchange,
    market_type,
    data_type,
    name,
    method,
    base_url,
    path,
    params_template,
    headers_template,
    response_format,
    is_batch_supported,
    batch_param_name,
    max_batch_size,
    rate_limit_per_second,
    rate_limit_per_minute,
    request_weight,
    min_interval_seconds,
    timeout_ms,
    is_active,
    notes
) VALUES
    -- Binance USD-M Futures
    ('binance', 'usds-m-futures', 'contracts', 'exchange_info', 'GET', 'https://fapi.binance.com', '/fapi/v1/exchangeInfo', '{}'::jsonb, '{}'::jsonb, 'json', true, NULL, 1000, 5, 300, 1, 0.200, 10000, true, 'Binance USD-M futures exchange information.'),
    ('binance', 'usds-m-futures', 'ticker', 'ticker_24hr', 'GET', 'https://fapi.binance.com', '/fapi/v1/ticker/24hr', '{"symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', true, 'symbol', 100, 5, 300, 1, 0.200, 10000, true, '24h ticker for USD-M futures.'),
    ('binance', 'usds-m-futures', 'mark_price', 'premium_index', 'GET', 'https://fapi.binance.com', '/fapi/v1/premiumIndex', '{"symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 5, 300, 1, 0.200, 10000, true, 'Premium index response includes mark price.'),
    ('binance', 'usds-m-futures', 'index_price', 'premium_index', 'GET', 'https://fapi.binance.com', '/fapi/v1/premiumIndex', '{"symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 5, 300, 1, 0.200, 10000, true, 'Premium index response includes index price.'),
    ('binance', 'usds-m-futures', 'kline', 'klines', 'GET', 'https://fapi.binance.com', '/fapi/v1/klines', '{"symbol":"{{source_symbol}}","interval":"{{period}}","startTime":"{{start_time}}","endTime":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 5, 300, 1, 0.200, 10000, true, 'USD-M futures klines.'),
    ('binance', 'usds-m-futures', 'open_interest', 'open_interest', 'GET', 'https://fapi.binance.com', '/fapi/v1/openInterest', '{"symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 5, 300, 1, 0.200, 10000, true, 'Current open interest.'),
    ('binance', 'usds-m-futures', 'open_interest_history', 'open_interest_hist', 'GET', 'https://fapi.binance.com', '/futures/data/openInterestHist', '{"symbol":"{{source_symbol}}","period":"{{period}}","startTime":"{{start_time}}","endTime":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 5, 300, 1, 0.200, 10000, true, 'Historical open interest.'),
    ('binance', 'usds-m-futures', 'funding', 'premium_index', 'GET', 'https://fapi.binance.com', '/fapi/v1/premiumIndex', '{"symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 5, 300, 1, 0.200, 10000, true, 'Current funding rate from premium index.'),
    ('binance', 'usds-m-futures', 'funding', 'funding_info', 'GET', 'https://fapi.binance.com', '/fapi/v1/fundingInfo', '{}'::jsonb, '{}'::jsonb, 'json', true, NULL, 1000, 5, 300, 1, 0.200, 10000, true, 'Funding info endpoint.'),
    ('binance', 'usds-m-futures', 'funding_history', 'funding_rate', 'GET', 'https://fapi.binance.com', '/fapi/v1/fundingRate', '{"symbol":"{{source_symbol}}","startTime":"{{start_time}}","endTime":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 5, 300, 1, 0.200, 10000, true, 'Historical funding rates.'),
    ('binance', 'usds-m-futures', 'long_short_ratio', 'global_long_short_account_ratio', 'GET', 'https://fapi.binance.com', '/futures/data/globalLongShortAccountRatio', '{"symbol":"{{source_symbol}}","period":"{{period}}","startTime":"{{start_time}}","endTime":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 5, 300, 1, 0.200, 10000, true, 'Global long/short account ratio.'),
    ('binance', 'usds-m-futures', 'long_short_ratio', 'top_long_short_account_ratio', 'GET', 'https://fapi.binance.com', '/futures/data/topLongShortAccountRatio', '{"symbol":"{{source_symbol}}","period":"{{period}}","startTime":"{{start_time}}","endTime":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 5, 300, 1, 0.200, 10000, true, 'Top trader account long/short ratio.'),
    ('binance', 'usds-m-futures', 'long_short_ratio', 'top_long_short_position_ratio', 'GET', 'https://fapi.binance.com', '/futures/data/topLongShortPositionRatio', '{"symbol":"{{source_symbol}}","period":"{{period}}","startTime":"{{start_time}}","endTime":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 5, 300, 1, 0.200, 10000, true, 'Top trader position long/short ratio.'),
    ('binance', 'usds-m-futures', 'taker_flow', 'taker_long_short_ratio', 'GET', 'https://fapi.binance.com', '/futures/data/takerlongshortRatio', '{"symbol":"{{source_symbol}}","period":"{{period}}","startTime":"{{start_time}}","endTime":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 5, 300, 1, 0.200, 10000, true, 'Taker buy/sell volume ratio.'),
    ('binance', 'usds-m-futures', 'basis', 'basis', 'GET', 'https://fapi.binance.com', '/futures/data/basis', '{"pair":"{{base_asset}}{{quote_asset}}","contractType":"PERPETUAL","period":"{{period}}","startTime":"{{start_time}}","endTime":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 5, 300, 1, 0.200, 10000, true, 'Basis endpoint uses pair rather than symbol.'),
    ('binance', 'usds-m-futures', 'orderbook', 'depth', 'GET', 'https://fapi.binance.com', '/fapi/v1/depth', '{"symbol":"{{source_symbol}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 5, 300, 2, 0.200, 10000, true, 'Order book depth summary source.'),
    ('binance', 'usds-m-futures', 'liquidation', 'all_force_orders', 'GET', 'https://fapi.binance.com', '/fapi/v1/allForceOrders', '{"symbol":"{{source_symbol}}","startTime":"{{start_time}}","endTime":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 5, 300, 20, 0.200, 10000, false, 'Seeded inactive until liquidation semantics and weight budget are verified for production use.'),

    -- OKX SWAP
    ('okx', 'swap', 'contracts', 'instruments', 'GET', 'https://www.okx.com', '/api/v5/public/instruments', '{"instType":"SWAP"}'::jsonb, '{}'::jsonb, 'json', true, NULL, 1000, 2, 120, 1, 0.500, 10000, true, 'OKX swap instruments.'),
    ('okx', 'swap', 'ticker', 'ticker', 'GET', 'https://www.okx.com', '/api/v5/market/ticker', '{"instId":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Single instrument ticker.'),
    ('okx', 'swap', 'kline', 'candles', 'GET', 'https://www.okx.com', '/api/v5/market/candles', '{"instId":"{{source_symbol}}","bar":"{{period}}","before":"{{start_time}}","after":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Market candles.'),
    ('okx', 'swap', 'mark_price', 'mark_price', 'GET', 'https://www.okx.com', '/api/v5/public/mark-price', '{"instType":"SWAP","instId":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Public mark price.'),
    ('okx', 'swap', 'index_price', 'index_tickers', 'GET', 'https://www.okx.com', '/api/v5/market/index-tickers', '{"instId":"{{base_asset}}-{{quote_asset}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, false, 'Inactive: index endpoint uses index instrument id, not swap source symbol.'),
    ('okx', 'swap', 'open_interest', 'open_interest', 'GET', 'https://www.okx.com', '/api/v5/public/open-interest', '{"instType":"SWAP","instId":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Current open interest.'),
    ('okx', 'swap', 'open_interest_history', 'rubik_open_interest_history', 'GET', 'https://www.okx.com', '/api/v5/rubik/stat/contracts/open-interest-history', '{"ccy":"{{base_asset}}","period":"{{period}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Rubik contract open interest history.'),
    ('okx', 'swap', 'funding', 'funding_rate', 'GET', 'https://www.okx.com', '/api/v5/public/funding-rate', '{"instId":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Current funding rate.'),
    ('okx', 'swap', 'funding_history', 'funding_rate_history', 'GET', 'https://www.okx.com', '/api/v5/public/funding-rate-history', '{"instId":"{{source_symbol}}","before":"{{start_time}}","after":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Funding rate history.'),
    ('okx', 'swap', 'long_short_ratio', 'long_short_account_ratio', 'GET', 'https://www.okx.com', '/api/v5/rubik/stat/contracts/long-short-account-ratio', '{"ccy":"{{base_asset}}","period":"{{period}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Rubik long/short account ratio.'),
    ('okx', 'swap', 'taker_flow', 'taker_volume', 'GET', 'https://www.okx.com', '/api/v5/rubik/stat/taker-volume', '{"ccy":"{{base_asset}}","instType":"SWAP","period":"{{period}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Rubik taker volume.'),
    ('okx', 'swap', 'orderbook', 'books', 'GET', 'https://www.okx.com', '/api/v5/market/books', '{"instId":"{{source_symbol}}","sz":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Order book depth.'),
    ('okx', 'swap', 'liquidation', 'liquidation_orders', 'GET', 'https://www.okx.com', '/api/v5/public/liquidation-orders', '{"instType":"SWAP","instId":"{{source_symbol}}","state":"filled","before":"{{start_time}}","after":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Public liquidation orders.'),

    -- Bybit V5 Linear
    ('bybit', 'linear', 'contracts', 'instruments_info', 'GET', 'https://api.bybit.com', '/v5/market/instruments-info', '{"category":"linear","symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', true, NULL, 1000, 3, 180, 1, 0.333, 10000, true, 'Bybit V5 linear instruments.'),
    ('bybit', 'linear', 'ticker', 'tickers', 'GET', 'https://api.bybit.com', '/v5/market/tickers', '{"category":"linear","symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 3, 180, 1, 0.333, 10000, true, 'Linear ticker.'),
    ('bybit', 'linear', 'kline', 'kline', 'GET', 'https://api.bybit.com', '/v5/market/kline', '{"category":"linear","symbol":"{{source_symbol}}","interval":"{{period}}","start":"{{start_time}}","end":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 3, 180, 1, 0.333, 10000, true, 'Market kline.'),
    ('bybit', 'linear', 'mark_price', 'mark_price_kline', 'GET', 'https://api.bybit.com', '/v5/market/mark-price-kline', '{"category":"linear","symbol":"{{source_symbol}}","interval":"{{period}}","start":"{{start_time}}","end":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 3, 180, 1, 0.333, 10000, true, 'Mark price kline.'),
    ('bybit', 'linear', 'index_price', 'index_price_kline', 'GET', 'https://api.bybit.com', '/v5/market/index-price-kline', '{"category":"linear","symbol":"{{source_symbol}}","interval":"{{period}}","start":"{{start_time}}","end":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 3, 180, 1, 0.333, 10000, true, 'Index price kline.'),
    ('bybit', 'linear', 'open_interest', 'open_interest', 'GET', 'https://api.bybit.com', '/v5/market/open-interest', '{"category":"linear","symbol":"{{source_symbol}}","intervalTime":"{{period}}","startTime":"{{start_time}}","endTime":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 3, 180, 1, 0.333, 10000, true, 'Open interest.'),
    ('bybit', 'linear', 'funding', 'tickers_current_funding', 'GET', 'https://api.bybit.com', '/v5/market/tickers', '{"category":"linear","symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 3, 180, 1, 0.333, 10000, true, 'Ticker includes current funding fields.'),
    ('bybit', 'linear', 'funding_history', 'funding_history', 'GET', 'https://api.bybit.com', '/v5/market/funding/history', '{"category":"linear","symbol":"{{source_symbol}}","startTime":"{{start_time}}","endTime":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 3, 180, 1, 0.333, 10000, true, 'Funding history.'),
    ('bybit', 'linear', 'long_short_ratio', 'long_short_ratio', 'GET', 'https://api.bybit.com', '/v5/market/long-short-ratio', '{"category":"linear","symbol":"{{source_symbol}}","period":"{{period}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 3, 180, 1, 0.333, 10000, true, 'Long/short ratio.'),
    ('bybit', 'linear', 'orderbook', 'orderbook', 'GET', 'https://api.bybit.com', '/v5/market/orderbook', '{"category":"linear","symbol":"{{source_symbol}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 3, 180, 1, 0.333, 10000, true, 'Order book depth.'),
    ('bybit', 'linear', 'liquidation', 'public_liquidation_history', 'GET', 'https://api.bybit.com', '/v5/market/liquidation', '{"category":"linear","symbol":"{{source_symbol}}","startTime":"{{start_time}}","endTime":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 3, 180, 1, 0.333, 10000, false, 'Inactive: public liquidation REST endpoint must be verified before collectors use it.'),

    -- Bitget USDT Futures, Classic Mix API v2
    ('bitget', 'usdt-futures', 'contracts', 'contracts_v2', 'GET', 'https://api.bitget.com', '/api/v2/mix/market/contracts', '{"productType":"USDT-FUTURES"}'::jsonb, '{}'::jsonb, 'json', true, NULL, 1000, 4, 240, 1, 0.250, 10000, true, 'Bitget Classic Mix API v2 contracts endpoint.'),
    ('bitget', 'usdt-futures', 'ticker', 'ticker_v2', 'GET', 'https://api.bitget.com', '/api/v2/mix/market/ticker', '{"productType":"USDT-FUTURES","symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 4, 240, 1, 0.250, 10000, true, 'Bitget Classic Mix API v2 ticker endpoint.'),
    ('bitget', 'usdt-futures', 'kline', 'candles_v2', 'GET', 'https://api.bitget.com', '/api/v2/mix/market/candles', '{"productType":"USDT-FUTURES","symbol":"{{source_symbol}}","granularity":"{{period}}","startTime":"{{start_time}}","endTime":"{{end_time}}","limit":"{{limit}}","kLineType":"MARKET"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 4, 240, 1, 0.250, 10000, true, 'Bitget Classic Mix API v2 market candles.'),
    ('bitget', 'usdt-futures', 'mark_price', 'symbol_price_v2', 'GET', 'https://api.bitget.com', '/api/v2/mix/market/symbol-price', '{"productType":"USDT-FUTURES","symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 4, 240, 1, 0.250, 10000, true, 'Symbol price endpoint includes mark/index/market prices.'),
    ('bitget', 'usdt-futures', 'index_price', 'symbol_price_v2', 'GET', 'https://api.bitget.com', '/api/v2/mix/market/symbol-price', '{"productType":"USDT-FUTURES","symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 4, 240, 1, 0.250, 10000, true, 'Symbol price endpoint includes index price.'),
    ('bitget', 'usdt-futures', 'open_interest', 'open_interest_v2', 'GET', 'https://api.bitget.com', '/api/v2/mix/market/open-interest', '{"productType":"USDT-FUTURES","symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 4, 240, 1, 0.250, 10000, true, 'Open interest endpoint.'),
    ('bitget', 'usdt-futures', 'funding', 'current_fund_rate_v2', 'GET', 'https://api.bitget.com', '/api/v2/mix/market/current-fund-rate', '{"productType":"USDT-FUTURES","symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 4, 240, 1, 0.250, 10000, true, 'Current funding rate.'),
    ('bitget', 'usdt-futures', 'funding', 'funding_time_v2', 'GET', 'https://api.bitget.com', '/api/v2/mix/market/funding-time', '{"productType":"USDT-FUTURES","symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 4, 240, 1, 0.250, 10000, true, 'Funding time endpoint.'),
    ('bitget', 'usdt-futures', 'funding_history', 'history_fund_rate_v2', 'GET', 'https://api.bitget.com', '/api/v2/mix/market/history-fund-rate', '{"productType":"USDT-FUTURES","symbol":"{{source_symbol}}","pageSize":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 4, 240, 1, 0.250, 10000, true, 'Historical funding rates.'),
    ('bitget', 'usdt-futures', 'long_short_ratio', 'account_long_short_v2', 'GET', 'https://api.bitget.com', '/api/v2/mix/market/account-long-short', '{"productType":"USDT-FUTURES","symbol":"{{source_symbol}}","period":"{{period}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 4, 240, 1, 0.250, 10000, true, 'Active long/short account data.'),
    ('bitget', 'usdt-futures', 'orderbook', 'merge_depth_v2', 'GET', 'https://api.bitget.com', '/api/v2/mix/market/merge-depth', '{"productType":"USDT-FUTURES","symbol":"{{source_symbol}}","limit":"{{limit}}","precision":"scale0"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 4, 240, 1, 0.250, 10000, true, 'Merged futures depth.'),

    -- Gate USDT Futures
    ('gate', 'usdt-futures', 'contracts', 'contracts', 'GET', 'https://api.gateio.ws', '/api/v4/futures/usdt/contracts', '{}'::jsonb, '{}'::jsonb, 'json', true, NULL, 1000, 2, 120, 1, 0.500, 10000, true, 'Gate USDT futures contracts.'),
    ('gate', 'usdt-futures', 'ticker', 'tickers', 'GET', 'https://api.gateio.ws', '/api/v4/futures/usdt/tickers', '{"contract":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Gate futures trading statistics.'),
    ('gate', 'usdt-futures', 'kline', 'candlesticks', 'GET', 'https://api.gateio.ws', '/api/v4/futures/usdt/candlesticks', '{"contract":"{{source_symbol}}","interval":"{{period}}","from":"{{start_time}}","to":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Gate futures candlesticks.'),
    ('gate', 'usdt-futures', 'mark_price', 'mark_candlesticks', 'GET', 'https://api.gateio.ws', '/api/v4/futures/usdt/candlesticks', '{"contract":"mark_{{source_symbol}}","interval":"{{period}}","from":"{{start_time}}","to":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Gate mark price candlesticks use mark_ contract prefix.'),
    ('gate', 'usdt-futures', 'index_price', 'index_candlesticks', 'GET', 'https://api.gateio.ws', '/api/v4/futures/usdt/candlesticks', '{"contract":"index_{{source_symbol}}","interval":"{{period}}","from":"{{start_time}}","to":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Gate index price candlesticks use index_ contract prefix.'),
    ('gate', 'usdt-futures', 'funding', 'tickers_current_funding', 'GET', 'https://api.gateio.ws', '/api/v4/futures/usdt/tickers', '{"contract":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Ticker includes current funding data.'),
    ('gate', 'usdt-futures', 'funding_history', 'funding_rate', 'GET', 'https://api.gateio.ws', '/api/v4/futures/usdt/funding_rate', '{"contract":"{{source_symbol}}","from":"{{start_time}}","to":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Historical funding rate.'),
    ('gate', 'usdt-futures', 'open_interest', 'contract_stats', 'GET', 'https://api.gateio.ws', '/api/v4/futures/usdt/contract_stats', '{"contract":"{{source_symbol}}","interval":"{{period}}","from":"{{start_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Contract stats include open interest.'),
    ('gate', 'usdt-futures', 'long_short_ratio', 'contract_stats', 'GET', 'https://api.gateio.ws', '/api/v4/futures/usdt/contract_stats', '{"contract":"{{source_symbol}}","interval":"{{period}}","from":"{{start_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Contract stats include long/short fields.'),
    ('gate', 'usdt-futures', 'taker_flow', 'contract_stats', 'GET', 'https://api.gateio.ws', '/api/v4/futures/usdt/contract_stats', '{"contract":"{{source_symbol}}","interval":"{{period}}","from":"{{start_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Contract stats include taker flow fields.'),
    ('gate', 'usdt-futures', 'orderbook', 'order_book', 'GET', 'https://api.gateio.ws', '/api/v4/futures/usdt/order_book', '{"contract":"{{source_symbol}}","limit":"{{limit}}","with_id":"true"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Gate futures order book.'),
    ('gate', 'usdt-futures', 'liquidation', 'liq_orders', 'GET', 'https://api.gateio.ws', '/api/v4/futures/usdt/liq_orders', '{"contract":"{{source_symbol}}","from":"{{start_time}}","to":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Gate public liquidation order history.'),
    ('gate', 'usdt-futures', 'basis', 'premium_index', 'GET', 'https://api.gateio.ws', '/api/v4/futures/usdt/premium_index', '{"contract":"{{source_symbol}}","interval":"{{period}}","from":"{{start_time}}","to":"{{end_time}}","limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Premium index kline chart.'),

    -- MEXC Futures
    ('mexc', 'usdt-futures', 'contracts', 'detail', 'GET', 'https://contract.mexc.com', '/api/v1/contract/detail', '{}'::jsonb, '{}'::jsonb, 'json', true, NULL, 1000, 2, 120, 1, 0.500, 10000, true, 'MEXC contract details.'),
    ('mexc', 'usdt-futures', 'ticker', 'ticker', 'GET', 'https://contract.mexc.com', '/api/v1/contract/ticker', '{"symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', true, 'symbol', 100, 2, 120, 1, 0.500, 10000, true, 'MEXC contract ticker.'),
    ('mexc', 'usdt-futures', 'kline', 'kline', 'GET', 'https://contract.mexc.com', '/api/v1/contract/kline/{{source_symbol}}', '{"interval":"{{period}}","start":"{{start_time}}","end":"{{end_time}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'MEXC contract kline.'),
    ('mexc', 'usdt-futures', 'index_price', 'index_price', 'GET', 'https://contract.mexc.com', '/api/v1/contract/index_price/{{source_symbol}}', '{}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'MEXC index price.'),
    ('mexc', 'usdt-futures', 'mark_price', 'fair_price', 'GET', 'https://contract.mexc.com', '/api/v1/contract/fair_price/{{source_symbol}}', '{}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'MEXC fair price as mark price.'),
    ('mexc', 'usdt-futures', 'funding', 'funding_rate', 'GET', 'https://contract.mexc.com', '/api/v1/contract/funding_rate/{{source_symbol}}', '{}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'MEXC current funding rate.'),
    ('mexc', 'usdt-futures', 'funding_history', 'funding_rate_history', 'GET', 'https://contract.mexc.com', '/api/v1/contract/funding_rate/history', '{"symbol":"{{source_symbol}}","page_num":"1","page_size":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'MEXC funding rate history.'),
    ('mexc', 'usdt-futures', 'orderbook', 'depth', 'GET', 'https://contract.mexc.com', '/api/v1/contract/depth/{{source_symbol}}', '{"limit":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'MEXC contract depth.'),
    ('mexc', 'usdt-futures', 'open_interest', 'ticker_open_interest', 'GET', 'https://contract.mexc.com', '/api/v1/contract/ticker', '{"symbol":"{{source_symbol}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, true, 'Ticker response includes position/open interest fields when available.'),
    ('mexc', 'usdt-futures', 'liquidation', 'public_liquidation_history', 'GET', 'https://contract.mexc.com', '/api/v1/contract/liquidation', '{"symbol":"{{source_symbol}}","start_time":"{{start_time}}","end_time":"{{end_time}}","page_size":"{{limit}}"}'::jsonb, '{}'::jsonb, 'json', false, NULL, 1, 2, 120, 1, 0.500, 10000, false, 'Inactive: liquidation endpoint is not part of the Phase 3 verified MEXC list.')
ON CONFLICT (exchange, market_type, data_type, name) DO UPDATE SET
    method = EXCLUDED.method,
    base_url = EXCLUDED.base_url,
    path = EXCLUDED.path,
    params_template = EXCLUDED.params_template,
    headers_template = EXCLUDED.headers_template,
    response_format = EXCLUDED.response_format,
    is_batch_supported = EXCLUDED.is_batch_supported,
    batch_param_name = EXCLUDED.batch_param_name,
    max_batch_size = EXCLUDED.max_batch_size,
    rate_limit_per_second = EXCLUDED.rate_limit_per_second,
    rate_limit_per_minute = EXCLUDED.rate_limit_per_minute,
    request_weight = EXCLUDED.request_weight,
    min_interval_seconds = EXCLUDED.min_interval_seconds,
    timeout_ms = EXCLUDED.timeout_ms,
    is_active = EXCLUDED.is_active,
    notes = EXCLUDED.notes,
    updated_at = now();
